services:
  spring-docker:
    image: bumoo/spring-docker:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  jenkins:
    image: jenkins/jenkins:jdk17
    platform: linux/amd64
    # Host: Container -> 포트 포워딩할 포트 지정
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ${HOST_JENKINS_HOME}:/var/jenkins_home
    links:
      - slave-1

  slave-1:
    image: jenkins/ssh-agent:jdk17
    platform: linux/amd64
    ports:
      - "2222:22" # SSH 포트
    volumes:
      - ${HOST_JENKINS_SLAVE_1}:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChR63d3v9lXYlWAkDWHe+hsPscnmt0EkJ6xxqaZ8KUVY06MZ9gwPb0PqAENKDErc87etftFHCgaI5zQrwlcuC4K3DxkbrVz0EIxWsy0OrtaBp2fRGQ1tCU71QhXhqjF/fLCvZBrNMpD9AO90RX9g+DZAFDyQmNZ8aCtbeScdLozfmdfjBuaE+DljlYhVxLsk7JQCbTlsHWH2WzcAQnGvkqtH/QimDkEoOv6xLQ03M0zHsLd94vN/40AESJpiwT2Qr0BlMULPf8JmjOR4dT2ZcRe/+RXEtqR/JLem7LhkIBfRvPvuKeH4RBdRz951VtcC5ORDKNslcQLLwTI5GSUcHZBtz2u22PZBj882vuR7dkO5uLK80toQQTX37xef8KLj4hmqirDJyse39Y3TywuaXCY5+3pmqhIfUCRcpG/aydJzKYLoRkh+pihZ/JbZlWEoGItRO6/bnRXiZiMRcJav8VeTZY8AyiVdnHw3d1T/VampcG93wtnCqv4L+57shEJRU=
